# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname dnorminvwish
#' @keywords internal
rmatn <- function(M, Q, P) {
    .Call(`_fdr_rmatn`, M, Q, P)
}

#' @rdname dnorminvwish
#' @keywords internal
rinvwish <- function(v, S) {
    .Call(`_fdr_rinvwish`, v, S)
}

#' @rdname dmultn
#' @keywords internal
rmultn <- function(m, Sigma) {
    .Call(`_fdr_rmultn`, m, Sigma)
}

dmultn <- function(x, m, Sigma, logd = FALSE) {
    .Call(`_fdr_dmultn`, x, m, Sigma, logd)
}

dmatn <- function(X, M, Q, P, logd = FALSE) {
    .Call(`_fdr_dmatn`, X, M, Q, P, logd)
}

dmatn2 <- function(X, M, Q, P, logd = FALSE) {
    .Call(`_fdr_dmatn2`, X, M, Q, P, logd)
}

#' @rdname dnorminvwish
#' @keywords internal
dinvwish <- function(Sigma, v, S, logd = FALSE) {
    .Call(`_fdr_dinvwish`, Sigma, v, S, logd)
}

